[package]
name = "statsd-monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
metrics = "0.22.3"
metrics-exporter-statsd = "0.7.0"

[[example]]
name = "client"